# Generated by Django 4.2 on 2023-04-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
